import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Appbar from '@/components/Appbar';
import { Providers } from '@/components/Providers';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} container mx-auto max-w-7xl px-2 antialiased md:px-0`}
        style={{ backgroundImage: `url("/grid.png")` }}
      >
        <Providers>
          <Appbar />
          {children}
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
